/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    users: User;
    profiles: Profile;
    'profile-content': ProfileContent;
    media: Media;
    'social-links': SocialLink;
    'featured-tracks': FeaturedTrack;
    themes: Theme;
    'instagram-connections': InstagramConnection;
    'instagram-posts': InstagramPost;
    'stripe-webhook-events': StripeWebhookEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    profiles: ProfilesSelect<false> | ProfilesSelect<true>;
    'profile-content': ProfileContentSelect<false> | ProfileContentSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'social-links': SocialLinksSelect<false> | SocialLinksSelect<true>;
    'featured-tracks': FeaturedTracksSelect<false> | FeaturedTracksSelect<true>;
    themes: ThemesSelect<false> | ThemesSelect<true>;
    'instagram-connections': InstagramConnectionsSelect<false> | InstagramConnectionsSelect<true>;
    'instagram-posts': InstagramPostsSelect<false> | InstagramPostsSelect<true>;
    'stripe-webhook-events': StripeWebhookEventsSelect<false> | StripeWebhookEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('pt-BR' | 'en') | ('pt-BR' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'pt-BR' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Operators with access to the Payload /admin panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * Application users. Mirrored from Supabase Auth; never edited directly except via the auth-sync webhook.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * UUID from Supabase auth.users. Authoritative identity key.
   */
  supabaseUserId: string;
  displayName?: string | null;
  role: 'user' | 'admin';
  plan: 'free' | 'pro';
  /**
   * Set on first profile creation; consumed by the trial-expiration cron (task-23).
   */
  trialEndsAt?: string | null;
  /**
   * Set on first checkout attempt (lazy customer creation). Webhook handler reads this to match incoming events.
   */
  stripeCustomerId?: string | null;
  /**
   * Set by `checkout.session.completed`; cleared by `customer.subscription.deleted`.
   */
  stripeSubscriptionId?: string | null;
  /**
   * Mirrored from Stripe webhooks. Null when no subscription has ever been created.
   */
  stripeSubscriptionStatus?: ('active' | 'past_due' | 'canceled') | null;
  /**
   * Wizard progress. Owned by the wizard server actions; do not edit directly from admin.
   */
  onboardingProgress?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles".
 */
export interface Profile {
  id: number;
  owner: number | User;
  slug: string;
  status: 'draft' | 'published' | 'unpublished' | 'paused';
  /**
   * Hero portrait. Renders on the public profile.
   */
  portrait?: (number | null) | Media;
  /**
   * Optional artist logo / monogram.
   */
  logo?: (number | null) | Media;
  /**
   * Gallery photos (drag-reorder in the editor). Max 50 (soft warn at 24).
   */
  gallery?: (number | Media)[] | null;
  /**
   * External press-kit URL (Google Drive, Dropbox, etc.). Provider + health are derived/checked automatically.
   */
  pressKitUrl?: string | null;
  /**
   * Derived from `pressKitUrl` by beforeChange hook.
   */
  pressKitProvider?:
    | ('unknown' | 'google-drive' | 'dropbox' | 'onedrive' | 'wetransfer' | 'notion' | 'mediafire' | 'other')
    | null;
  /**
   * Updated by the daily health-check cron (task-30).
   */
  pressKitLastCheckedAt?: string | null;
  /**
   * Set by the daily cron (task-30).
   */
  pressKitHealthStatus?: ('unknown' | 'healthy' | 'warning' | 'broken') | null;
  /**
   * Public WhatsApp contact (E.164, e.g. +5511999999999). Editor canonicalizes; the public profile renders a wa.me link.
   */
  contactWhatsapp?: string | null;
  /**
   * Public contact email. Defaults the contact-form destination if left empty there.
   */
  contactEmail?: string | null;
  /**
   * Show the contact form on the public profile. When off, only the WhatsApp / email buttons render.
   */
  contactFormEnabled?: boolean | null;
  /**
   * Destination email for form submissions. Falls back to `contactEmail` when empty.
   */
  contactFormDestination?: string | null;
  defaultLocale: 'pt-BR' | 'en';
  /**
   * Locales with published content. The public profile uses this to gate the locale toggle (task-19).
   */
  localesAvailable?: ('pt-BR' | 'en')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reference-only metadata for files stored in Supabase Storage. Payload does NOT manage the underlying file (no `upload: true`). See ADR 0001.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  bucket: 'avatars' | 'gallery';
  /**
   * Path within the bucket. Combined with bucket → public URL at render time.
   */
  path: string;
  mimeType: string;
  /**
   * Bytes.
   */
  size: number;
  width?: number | null;
  height?: number | null;
  /**
   * Required for a11y unless `decorative` is true (in which case the public render emits alt="").
   */
  alt?: string | null;
  /**
   * Mark for purely-decorative images (textures, abstract bg). Public render emits alt="" (WCAG-correct).
   */
  decorative?: boolean | null;
  owner: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile-content".
 */
export interface ProfileContent {
  id: number;
  profile: number | Profile;
  tagline?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  services?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Hero call-to-action label. Editor presets: "Contato para shows" / "Book now" / custom.
   */
  ctaLabel?: string | null;
  /**
   * CTA destination — e.g. mailto:press@x.com, tel:+5511..., https://wa.me/55..., or any https:// URL. Same value across locales.
   */
  ctaUrl?: string | null;
  /**
   * SEO <title>. Falls back to display name + tagline if empty.
   */
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * Open Graph image. Falls back to hero portrait if empty.
   */
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links".
 */
export interface SocialLink {
  id: number;
  profile: number | Profile;
  platform:
    | 'instagram'
    | 'tiktok'
    | 'soundcloud'
    | 'spotify'
    | 'youtube'
    | 'twitter'
    | 'bandcamp'
    | 'mixcloud'
    | 'apple-music'
    | 'beatport'
    | 'whatsapp'
    | 'email'
    | 'website';
  url: string;
  /**
   * Lower = earlier on the public profile.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-tracks".
 */
export interface FeaturedTrack {
  id: number;
  profile: number | Profile;
  /**
   * Other providers (Spotify, Bandcamp) land in v2.
   */
  provider: 'soundcloud';
  url: string;
  /**
   * Cached oEmbed HTML. Refreshed when stale (task-16).
   */
  oembedHtml?: string | null;
  /**
   * When the oEmbed cache was last refreshed.
   */
  fetchedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes".
 */
export interface Theme {
  id: number;
  profile: number | Profile;
  /**
   * BG preset id (e.g. 'editorial-night'). Empty when overriding via custom hex.
   */
  colorPresetId?: string | null;
  /**
   * Accent preset id (e.g. 'electric-green'). Empty when overriding via custom hex.
   */
  accentPresetId?: string | null;
  /**
   * Hex value, present when overriding the preset bg.
   */
  bg?: string | null;
  /**
   * Hex value, present when overriding the preset accent.
   */
  accent?: string | null;
  /**
   * Hex value; auto-derived if empty.
   */
  text?: string | null;
  fontPairId:
    | 'editorial-nightlife'
    | 'magazine'
    | 'brutalist'
    | 'refined'
    | 'industrial'
    | 'soft-pop'
    | 'retro-future'
    | 'classic-press';
  heroStyle: 'full-bleed-portrait' | 'split-portrait-text' | 'centered-logo';
  galleryLayout: 'mosaic' | 'uniform-grid' | 'carousel';
  /**
   * Order of editor-managed sections on the public profile.
   */
  sectionOrder?:
    | {
        key: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Updated by the editor when the contrast gate passes. Profile publish is blocked if null or stale.
   */
  contrastValidatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * IG access tokens are encrypted at rest. Never paste tokens into the admin UI directly — use the editor flow (task-17).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-connections".
 */
export interface InstagramConnection {
  id: number;
  profile: number | Profile;
  /**
   * Instagram user id from the Graph API.
   */
  igUserId: string;
  /**
   * Encrypted at rest. Decryption happens in afterRead for admin/server use only.
   */
  accessToken: string;
  tokenExpiresAt: string;
  /**
   * When the IG feed cache was last refreshed.
   */
  lastSyncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-posts".
 */
export interface InstagramPost {
  id: number;
  profile: number | Profile;
  url: string;
  /**
   * Sanitized embed HTML — either Graph-oEmbed iframe or our blockquote fallback. Refreshed by the editor.
   */
  oembedHtml?: string | null;
  /**
   * Lower = earlier on the public profile.
   */
  displayOrder?: number | null;
  /**
   * When the embed cache was last refreshed.
   */
  fetchedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Stripe webhook idempotency log. Read-only — written by /api/webhooks/stripe.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stripe-webhook-events".
 */
export interface StripeWebhookEvent {
  id: number;
  /**
   * Stripe's `event.id`. Unique constraint enforces idempotency.
   */
  eventId: string;
  /**
   * Stripe's `event.type` (e.g. checkout.session.completed).
   */
  eventType: string;
  processedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'profiles';
        value: number | Profile;
      } | null)
    | ({
        relationTo: 'profile-content';
        value: number | ProfileContent;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'social-links';
        value: number | SocialLink;
      } | null)
    | ({
        relationTo: 'featured-tracks';
        value: number | FeaturedTrack;
      } | null)
    | ({
        relationTo: 'themes';
        value: number | Theme;
      } | null)
    | ({
        relationTo: 'instagram-connections';
        value: number | InstagramConnection;
      } | null)
    | ({
        relationTo: 'instagram-posts';
        value: number | InstagramPost;
      } | null)
    | ({
        relationTo: 'stripe-webhook-events';
        value: number | StripeWebhookEvent;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  supabaseUserId?: T;
  displayName?: T;
  role?: T;
  plan?: T;
  trialEndsAt?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  stripeSubscriptionStatus?: T;
  onboardingProgress?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles_select".
 */
export interface ProfilesSelect<T extends boolean = true> {
  owner?: T;
  slug?: T;
  status?: T;
  portrait?: T;
  logo?: T;
  gallery?: T;
  pressKitUrl?: T;
  pressKitProvider?: T;
  pressKitLastCheckedAt?: T;
  pressKitHealthStatus?: T;
  contactWhatsapp?: T;
  contactEmail?: T;
  contactFormEnabled?: T;
  contactFormDestination?: T;
  defaultLocale?: T;
  localesAvailable?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile-content_select".
 */
export interface ProfileContentSelect<T extends boolean = true> {
  profile?: T;
  tagline?: T;
  bio?: T;
  services?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaUrl?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  bucket?: T;
  path?: T;
  mimeType?: T;
  size?: T;
  width?: T;
  height?: T;
  alt?: T;
  decorative?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  profile?: T;
  platform?: T;
  url?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-tracks_select".
 */
export interface FeaturedTracksSelect<T extends boolean = true> {
  profile?: T;
  provider?: T;
  url?: T;
  oembedHtml?: T;
  fetchedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes_select".
 */
export interface ThemesSelect<T extends boolean = true> {
  profile?: T;
  colorPresetId?: T;
  accentPresetId?: T;
  bg?: T;
  accent?: T;
  text?: T;
  fontPairId?: T;
  heroStyle?: T;
  galleryLayout?: T;
  sectionOrder?:
    | T
    | {
        key?: T;
        id?: T;
      };
  contrastValidatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-connections_select".
 */
export interface InstagramConnectionsSelect<T extends boolean = true> {
  profile?: T;
  igUserId?: T;
  accessToken?: T;
  tokenExpiresAt?: T;
  lastSyncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-posts_select".
 */
export interface InstagramPostsSelect<T extends boolean = true> {
  profile?: T;
  url?: T;
  oembedHtml?: T;
  displayOrder?: T;
  fetchedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stripe-webhook-events_select".
 */
export interface StripeWebhookEventsSelect<T extends boolean = true> {
  eventId?: T;
  eventType?: T;
  processedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}